export const BAR_CREATE = `BAR_CREATE`
export const BAR_UPDATE = `BAR_UPDATE`
export const BAR_DELETE = `BAR_DELETE`

export const NIGHT_CREATE = `NIGHT_CREATE`
export const NIGHT_COMPUTE = `NIGHT_COMPUTE`
export const NIGHT_DELETE = `NIGHT_DELETE`
export const NIGHT_ARTICLE_ADD = `NIGHT_ARTICLE_ADD`
export const NIGHT_ARTICLE_REMOVE = `NIGHT_ARTICLE_REMOVE`
export const NIGHT_PERSON_ADD = `NIGHT_PERSON_ADD`
export const NIGHT_PERSON_REMOVE = `NIGHT_PERSON_REMOVE`

export const RESET = `RESET`
