export const M_BAR_CREATE = `M_BAR_CREATE`
export const M_BAR_UPDATE = `M_BAR_UPDATE`
export const M_BAR_DELETE = `M_BAR_DELETE`
export const M_BAR_RESET = `M_BAR_RESET`

export const M_NIGHT_CREATE = `M_NIGHT_CREATE`
export const M_NIGHT_COMPUTE = `M_NIGHT_COMPUTE`
export const M_NIGHT_DELETE = `M_NIGHT_DELETE`
export const M_NIGHT_ARTICLE_ADD = `M_NIGHT_ARTICLE_ADD`
export const M_NIGHT_ARTICLE_REMOVE = `M_NIGHT_ARTICLE_REMOVE`
export const M_NIGHT_PERSON_ADD = `M_NIGHT_PERSON_ADD`
export const M_NIGHT_PERSON_REMOVE = `M_NIGHT_PERSON_REMOVE`
export const M_NIGHT_RESET = `M_NIGHT_RESET`

export const M_SETTINGS_UPDATE = `M_SETTINGS_UPDATE`
